version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  versioning-strategy: widen
  ignore:
  - dependency-name: redis
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: p-finally
    versions:
    - 2.0.1
  commit-message:
    prefix: chore
    include: scope
